### ISSUE TITLE
Rare world generation crash

### ISSUE THREAD

**Issue by Gorenebeda** [CalaMariGold/TREPIDATION#1]
=======Pack Info======= 

IGN: GoreNeBeda
Pack Version: 0.2.3
MC Version: 1.12.2
Forge Version: 14.23.5.2860
Mods Loaded: 171

=======System Info======= 

Operating System: Windows 10
Java: 1.8.0_51 64bit
CPU: 16x AMD Ryzen 7 PRO 2700 Eight-Core Processor 
Display: NVIDIA GeForce RTX 3070/PCIe/SSE2
Mem:  30% 2224/7225MB
Allocated:  76% 5519MB

======= Issue ======= 
 
Title: Rare world generation crash 
 
--------------------------- 
Description: i have ate soul bead, roamed around for around 30 seconds and the game has suddenly crashed

=======CrashLog======= 
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2022-06-11 10:53:52 NOVT
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
    at net.minecraft.world.World.neighborChanged(World.java:557)
    at net.minecraft.world.World.notifyNeighborsOfStateChange(World.java:496)
    at net.minecraft.world.World.notifyNeighborsRespectDebug(World.java:440)
    at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
    at net.minecraft.world.World.setBlockState(World.java:361)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:153)
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at net.minecraft.block.BlockDynamicLiquid.onBlockAdded(BlockDynamicLiquid.java:306)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:133)
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at net.minecraft.block.BlockDynamicLiquid.onBlockAdded(BlockDynamicLiquid.java:306)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:153)
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at net.minecraft.block.BlockDynamicLiquid.onBlockAdded(BlockDynamicLiquid.java:306)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:133)
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at net.minecraft.block.BlockDynamicLiquid.onBlockAdded(BlockDynamicLiquid.java:306)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:153)
    at net.minecraft.world.WorldServer.updateBlockTick(WorldServer.java:551)
    at net.minecraft.world.WorldServer.scheduleUpdate(WorldServer.java:531)
    at net.minecraft.block.BlockDynamicLiquid.onBlockAdded(BlockDynamicLiquid.java:306)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.block.BlockDynamicLiquid.tryFlowInto(BlockDynamicLiquid.java:175)
    at net.minecraft.block.BlockDynamicLiquid.updateTick(BlockDynamicLiquid.java:153)
    at net.minecraft.world.World.immediateBlockTick(World.java:2682)
    at net.minecraft.world.gen.feature.WorldGenHellLava.generate(WorldGenHellLava.java:92)
    at net.minecraft.world.gen.ChunkGeneratorHell.populate(ChunkGeneratorHell.java:390)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1019)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:985)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.world.World.getChunk(World.java:310)
    at net.minecraft.world.World.getChunk(World.java:305)
    at net.minecraft.world.World.getBlockState(World.java:911)
    at net.minecraft.world.chunk.Chunk.enqueueRelightChecks(Chunk.java:1282)
    at net.minecraft.world.WorldServer.updateBlocks(WorldServer.java:398)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:225)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: New World
  All players: 1 total; [EntityPlayerMP['GoreNeBeda'/0, l='New World', x=-25.35, y=81.00, z=-68.65]]
  Chunk stats: ServerChunkCache: 1179 Drop: 0
  Level seed: -3848764793186586534
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 0 game time, 0 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: ~~ERROR~~ NullPointerException: null

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1629316712 bytes (1553 MB) / 4438097920 bytes (4232 MB) up to 7575961600 bytes (7225 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8128m -Xms256m
  IntCache: cache: 0, tcache: 43, allocated: 1, tallocated: 18
  FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
  Loaded coremods (and transformers): KonkreteCore (konkrete_forge_1.3.3_MC_1.12-1.12.2.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      ClsPlugin (CustomLoadingScreen-1.12.2-1.5.7.jar)
                                        alexiil.mc.mod.load.coremod.ClsTransformer
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
                                        lumien.perfectspawn.asm.ClassTransformer
                                      BlurPlugin (Blur-1.0.4-14.jar)
                                        com.tterrag.blur.BlurTransformer
                                      RenderLibPlugin (RenderLib-1.12.2-1.0.7.jar)
                                        meldexun.renderlib.asm.RenderLibClassTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.3.jar)
                                        bre.smoothfont.asm.Transformer
                                      LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
                                        lumien.resourceloader.asm.ClassTransformer
                                      ToolProgressionPlugin (toolprogression-core-1.12.2-1.6.12.jar)
                                        tyra314.toolprogression.core.asm.ToolProgressionClassTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-6.0.2.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      ReBind Core (rebind-1.12.2-2.7.5-0.jar)
                                        austeretony.rebind.common.core.ReBindClassTransformer
                                      Vertically Stacked Dimensions ASM (VerticallyStackedDimensions-1.12.2-0.1.9.jar)
                                        cd4017be.dimstack.asm.ChunkPrimerTransformer
                                        cd4017be.dimstack.asm.BlockPortalTransformer
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
                                      RandomPatches (randompatches-1.12.2-1.22.1.10.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      Quark Plugin (QuarkRotN-r1.6-185.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.70_mc1.12.2.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      DupeFixProjectCoreMod (DupeFixProject-1.12.2-3.1.6.jar)
                                        
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
                                        
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      FMCore (fancymenu_forge_2.7.2_MC_1.12-1.12.2.jar)
                                        
                                      MixinBooter (!mixinbooter-4.2.jar)
                                        
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      BNBGamingCore (BNBGamingCore-1.12.2-0.12.0.jar)
                                        com.bloodnbonesgaming.bnbgamingcore.core.BNBGamingCoreClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      ExampleModLoadingPlugin (maleksinfinitygauntlet.jar)
                                        
                                      Aqua Acrobatics Transformer (AquaAcrobatics-1.14.1.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Unknown
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['GoreNeBeda'/0, l='New World', x=-25.35, y=81.00, z=-68.65]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by CalaMariGold** [comment]
This doesn't seem to do anything with the soul bead, but a bug in the world generation. No specific mod is mentioned in the crash log either so it might just be a rare world gen bug.

Let me know if this happens again.

**Comment by CalaMariGold** [comment]
May or may not be related, but I tested 0.2.9 with Lag Goggles and noticed lava blocks are incredibly laggy for the server.

Something is messing with BlockDynamicLiquid maybe

**Comment by CalaMariGold** [comment]
If anyone encounters this crash in the latest version, please post here.

**Comment by Gorenebeda** [comment]
[crash-2023-02-23_03.10.29-server.txt](https://github.com/CalaMariGold/TREPIDATION/files/10808470/crash-2023-02-23_03.10.29-server.txt)
new crash log

**Comment by CalaMariGold** [comment]
After many hours of dev work, I haven't come across the crash in months. I'm assuming it was fixed in a previous version. Please reopen this issue if anyone comes across this same exact crash.
